# Generated by Django 4.1.3 on 2022-11-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_page_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='short_description',
            field=models.CharField(max_length=32),
        ),
    ]
