# Generated by Django 4.1.3 on 2022-11-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_page_html_content_alter_page_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='html_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
