# Generated by Django 4.1.3 on 2022-11-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_page_html_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='short_description',
            new_name='short',
        ),
    ]
