# Generated by Django 4.1.3 on 2022-11-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_rename_short_description_page_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='have_comments',
            field=models.BooleanField(default=True),
        ),
    ]
