# Generated by Django 4.1.3 on 2022-12-17 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0008_remove_comment_page_remove_comment_reply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.BooleanField()),
                ('url', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=128)),
                ('main_image', models.ImageField(upload_to='Media/video/main/')),
                ('bg_image', models.ImageField(upload_to='Media/video/bg/')),
                ('release_date', models.DateField()),
                ('duration', models.FloatField()),
                ('trailer_yt_url', models.CharField(max_length=128)),
                ('imdb_url', models.CharField(max_length=128)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('actors', models.ManyToManyField(to='Main.actor')),
                ('coutries', models.ManyToManyField(to='Main.country')),
                ('genres', models.ManyToManyField(to='Main.genre')),
                ('producers', models.ManyToManyField(to='Main.producer')),
                ('tags', models.ManyToManyField(to='Main.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.video')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.season')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.country'),
        ),
    ]
