# Generated by Django 4.1.3 on 2022-12-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
