# Generated by Django 4.1.3 on 2022-12-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_season_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='country',
        ),
    ]
