# Generated by Django 4.1.3 on 2022-12-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_remove_actor_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='url',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
