# Generated by Django 4.1.3 on 2022-12-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_episode_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='url',
            field=models.CharField(max_length=1024),
        ),
    ]
