# Generated by Django 4.1.3 on 2022-12-17 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_alter_episode_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/video/bg')),
            ],
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/video/main')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='bg_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.bgimage'),
        ),
        migrations.AlterField(
            model_name='video',
            name='main_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.mainimage'),
        ),
    ]
