# Generated by Django 4.1.3 on 2022-12-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_bgimage_mainimage_alter_video_bg_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
