# Generated by Django 4.1.5 on 2023-01-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_alter_image_image_alter_video_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='actors',
            field=models.ManyToManyField(to='Main.actor'),
        ),
        migrations.AlterField(
            model_name='video',
            name='coutries',
            field=models.ManyToManyField(to='Main.country'),
        ),
        migrations.AlterField(
            model_name='video',
            name='genres',
            field=models.ManyToManyField(to='Main.genre'),
        ),
        migrations.AlterField(
            model_name='video',
            name='producers',
            field=models.ManyToManyField(to='Main.producer'),
        ),
    ]
